// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID            string
	Email         string
	EmailVerified bool
	IsBanned      bool
	Subscribed    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
