// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email)
VALUES (
    $1,
    $2
)
RETURNING id
`

type CreateUserParams struct {
	ID    string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteUsers = `-- name: DeleteUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsers)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email, email_verified, is_banned, subscribed, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.IsBanned,
		&i.Subscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, is_banned, subscribed, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.IsBanned,
		&i.Subscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, email, email_verified, is_banned, subscribed, created_at, updated_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.IsBanned,
			&i.Subscribed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserEmailVerified = `-- name: SetUserEmailVerified :one
UPDATE users
SET email_verified = $2
WHERE id = $1
RETURNING id, email, email_verified, is_banned, subscribed, created_at, updated_at
`

type SetUserEmailVerifiedParams struct {
	ID            string
	EmailVerified bool
}

func (q *Queries) SetUserEmailVerified(ctx context.Context, arg SetUserEmailVerifiedParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserEmailVerified, arg.ID, arg.EmailVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.IsBanned,
		&i.Subscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
