name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      supabase:
        image: supabase/postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://get.supabase.com/install | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      - name: Start Supabase locally
        run: supabase start

      - name: Set up environment variables
        run: |
          echo "SUPABASE_URL=http://localhost:54321" >> $GITHUB_ENV
          echo "SUPABASE_KEY=your-local-anon-key" >> $GITHUB_ENV
          echo "SUPABASE_SERVICE_ROLE_KEY=your-local-service-role-key" >> $GITHUB_ENV
          echo "PORT=8080" >> $GITHUB_ENV

      - name: Start application
        run: go run .

      - name: Run Integration Tests
        run: go test -v ./integration_tests
